version: "3"
services:

    loadbalancer:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - "c-network"
      command: "nginx -g 'daemon off;'"
      environment:
        - NGINX_HOST=ecomarket.works
        - NGINX_PORT=80
      restart: always
    
    app:
      build: ./ecomarket-app/   
      networks:
        - "c-network"
      restart: always

    mysql_master:
      image: mysql:debian
      networks:
        - "c-network"
      restart: always
    
    mysql_slave:
      image: mysql:debian
      networks:
        - "c-network"
      restart: always

networks:
    c-network:
    auth-service: