version: "3"
services:

    loadbalancer:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - "c-network"
      command: "nginx -g 'daemon off;'"
      environment:
        - NGINX_HOST=ecomarket.works
        - NGINX_PORT=80
      restart: always
    
    # frontend:
    #   build: ./ecomarket-app/ecomarket-frontend    
    #   networks:
    #     c-network:
    #       aliases:
    #         - frontend
    #   restart: always
    #   depends_on:
    #     - "loadbalancer"

    # backend:
    #   build: ./ecomarket-app/ecomarket-backend 
    #   networks:
    #     c-network:
    #       aliases:
    #         - backend
    #   restart: always
    #   depends_on:
    #     - "frontend"
    #    # - "mysql_master"

    frontend:
      image: node:18-bullseye
      container_name: frontend
      volumes:
        - ./ecomarket-app/ecomarket-frontend:/frontend
      command: "npm start --prefix /frontend"
      networks:
        c-network:
          aliases:
            - frontend
      restart: always
      depends_on:
        - "loadbalancer"

    backend:
      image: node:18-bullseye
      container_name: backend
      volumes:
        - ./ecomarket-app/ecomarket-backend:/backend
      command: "node ./backend/bin/www"
      networks:
        c-network:
          aliases:
            - backend
      restart: always
      depends_on:
        - "frontend"

networks:
    c-network:

volumes:
    #volume for where sql data is stored
    data:
