version: "3"
services:

    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      networks:
        - "c-network"
      command: [nginx-debug, '-g', 'daemon off;']
      environment:
        - NGINX_HOST=ecomarket.works
        - NGINX_PORT=80
    
    backend:
      build: ./ecomarket-app/   
      networks:
        - "c-network"

    mysql_master:
      image: mysql:debian
      networks:
        - "c-network"
    
    mysql_slave:
      image: mysql:debian
      networks:
        - "c-network"

networks:
    c-network:
    auth-service: