version: "3"
services:

    loadbalancer:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - "c-network"
      command: "nginx -g 'daemon off;'"
      environment:
        - NGINX_HOST=ecomarket.works
        - NGINX_PORT=80
      restart: always
    
    # frontend:
    #   build: ./ecomarket-app/ecomarket-frontend    
    #   networks:
    #     c-network:
    #       aliases:
    #         - frontend
    #   restart: always
    #   depends_on:
    #     - "loadbalancer"

    # backend:
    #   build: ./ecomarket-app/ecomarket-backend 
    #   networks:
    #     c-network:
    #       aliases:
    #         - backend
    #   restart: always
    #   depends_on:
    #     - "frontend"
    #    # - "mysql_master"

    frontend:
      image: node:18-bullseye
      volumes:
        - ./ecomarket-app/ecomarket-frontend:/frontend
      command: "cd /frontend && npm start"
      networks:
        c-network:
          aliases:
            - frontend
      restart: always
      depends_on:
        - "loadbalancer"

    backend:
      image: node:18-bullseye
      volumes:
        - ./ecomarket-app/ecomarket-backend:/backend
      command: "cd /backend && npm start"
      networks:
        c-network:
          aliases:
            - backend
      restart: always
      depends_on:
        - "frontend"
       # - "mysql_master"

    mysql_master:
      image: mysql:debian
      networks:
        c-network:
          aliases:
            - mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=S3cret
        - MYSQL_PASSWORD=An0thrS3crt
        - MYSQL_USER=user
        #- DATA_SAVE_PATH=../data
      volumes:
        - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
        - ./database/hello.sql:/docker-entrypoint-initdb.d/hello.sql
        - data:/var/lib/mysql
      
      stdin_open: true # docker run -i
      tty: true        # docker run -t


    # mysql_slave:
    #   image: mysql:debian
    #   networks:
    #     - "c-network"
    #   #restart: always
    #   depends_on:
    #     - "mysql_master"

networks:
    c-network:
    auth-service:

volumes:
    #volume for where sql data is stored
    data:
