version: "3"
services:

    loadbalancer:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
        - "c-network"
      command: "nginx -g 'daemon off;'"
      environment:
        - NGINX_HOST=ecomarket.works
        - NGINX_PORT=80
      restart: always
    
    frontend:
      build: ./ecomarket-app/ecomarket-frontend    
      networks:
        c-network:
          aliases:
            - frontend
      restart: always
      depends_on:
        - "backend"

    backend:
      build: ./ecomarket-app/ecomarket-backend 
      networks:
        c-network:
          aliases:
            - backend
      restart: always
      depends_on:
        - "loadbalancer"
        - "mysql_master"

    mysql_master:
      image: mysql:debian
      networks:
        c-network:
          aliases:
            - mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=S3cret
        - MYSQL_PASSWORD=An0thrS3crt
        - MYSQL_USER=user
      volumes:
        - ./database/db.sql:/docker-entrypoint-initdb.d/init.sql
        - data:/var/lib/mysql
      
      stdin_open: true # docker run -i
      tty: true        # docker run -t


    mysql_slave:
      image: mysql:debian
      networks:
        - "c-network"
      #restart: always
      depends_on:
        - "mysql_master"

networks:
    c-network:
    auth-service:

volumes:
    #volume for where sql data is stored
    data:
