version: "3"
services:       
    database:
      image: mysql:debian
      networks:
        db-network:
          aliases:
            - mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=S3cret
        - MYSQL_PASSWORD=An0thrS3crt
        - MYSQL_USER=user
        #- DATA_SAVE_PATH=../data
      volumes:
        - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
        - ./database/hello.sql:/docker-entrypoint-initdb.d/hello.sql
        - data:/var/lib/mysql
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      container_name: db_container
     # command:
networks:
    db-network:
      driver: bridge
      ipam:
        config:
          - subnet: 10.0.1.0/29


volumes:
    #volume for where sql data is stored
    data:
