version: "3"
services:       
    database:
      image: mysql:debian
      networks:
        db-network:
          aliases:
            - mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=S3cret
        - MYSQL_PASSWORD=An0thrS3crt
        - MYSQL_USER=user
        #- DATA_SAVE_PATH=../data
      volumes:
        - ./db.sql:/docker-entrypoint-initdb.d/db.sql
        - ./hello.sql:/docker-entrypoint-initdb.d/hello.sql
        - data:/var/lib/mysql
        - ./conf.cnf:/etc/mysql/conf.cnf 
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      #command: [ "mysqld","--loose-group-replication-local-address=alpha:6606" ]
      scale: 3
networks:
    db-network:
      driver: bridge
      ipam:
        config:
          - subnet: 10.0.1.0/29


volumes:
    #volume for where sql data is stored
    data:
